import "./globals.css";
import { StepProvider } from "../contexts/StepContext";
import { CoinProvider } from "../contexts/CoinContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StepProvider>
          <CoinProvider>{children}</CoinProvider>
        </StepProvider>
      </body>
    </html>
  );
}
