import "./globals.css";
import { StepProvider } from "../contexts/StepContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StepProvider>{children}</StepProvider>
      </body>
    </html>
  );
}
